### ISSUE TITLE
Issue maintenance

### ISSUE THREAD

**Issue by TonioGela** [foundweekends/giter8#575]
I read almost all the issues still open and in my opinion the following ones can be closed since they've been somehow handled:
- [x] #478: 'skip_folder' being generated
- [x] #162: g8 command not recognized during install process-Ubuntu 14.04
- [x] #289: Support applying templates from a custom tag or branch
- [x] #227: installation instructions don't quite work
- [x] #238: Install giter8 in offline mode
- [x] #273: Document template comment syntax (once #573 gets merged)
- [x] #504: Is there a way to generate the files and directories in a specified folder? (once #574 gets merged)
- [x] #336: Unable do download sbt-giter8-scaffold.jar (outdated)
- [x] #396: Doc: Add command arguments to the documentation (once #574 gets merged)

**Comment by eed3si9n** [comment]
Thanks!

**Comment by eed3si9n** [comment]
ok I've closed / merged them all.

**Comment by eed3si9n** [comment]
I've also invited you to a member team that has triage rights so feel free to close issues :)

**Comment by TonioGela** [comment]
> I've also invited you to a member team that has triage rights so feel free to close issues :)

Thanks! I'll do my best ;)
